**Pandas **

It is a python library which is used for Data Manipulation and Data Analysis. It helps you to load, clean, Transform, analyze and explore the data. It stands for Pannel Data.

**Why was pandas created **
As we know Numpy is amazing for working with numbers, arrays and perform mathematical operations. But real - world data is messy :- missing values, mixed data, it is not clean,CSV/Excel file so, pandas was created to handle the real world problems, not only just for mathematics

**Pandas helps in -**

In [ ]:
# 1 - Load the dataset(CSV, Excel........)
# 2 - To clean the data(remove the null values, duplicate values, to handle null values,wrong values)
# 3 - to maipulate the data(filter, sort, group, merge...)
# 4 - to analyze the data for Machine Learning Models

In [ ]:
import pandas as pd

In [ ]:
# Pandas mainly has two structures -
# 1 - Series
# 2- DataFrame

**Series**
    it is one-dimensional array labeled array
    it is simply one column data with an index
    it can store number, string or mixed datatype

**Series = Data + Index**

In [ ]:
# Creating a Series -

**1- From a list**

In [ ]:
# to create a series ----> pd.Series
s = pd.Series([30,40,50,60,61,80,90])
print(s)

0    30
1    40
2    50
3    60
4    61
5    80
6    90
dtype: int64

In [ ]:
print(type(s))

<class 'pandas.core.series.Series'>

**2 - From a python dictionary**

In [ ]:
d1 = {'A':101, 'hii':102, 103:'Hello', 'A':'red'}
s2 = pd.Series(d1)
print(s2)
# Note - Keys in dictionary act as label
# values in dict act as data in series

A        red
hii      102
103    Hello
dtype: object

**3 - from tuple**

In [ ]:
t = (31,32,33,34,46)
s4 = pd.Series(t)
print(s4)

0    31
1    32
2    33
3    34
4    46
dtype: int64

In [ ]:
s = pd.Series([10,20,[30,40],50])
print(s)
print(type(s))

0          10
1          20
2    [30, 40]
3          50
dtype: object
<class 'pandas.core.series.Series'>

**4 - Custom Label/index**

In [ ]:
a1 = pd.Series([100,200,300,400], index = ['a','b','c','d'])
print(a1)

a    100
b    200
c    300
d    400
dtype: int64

**Accessing Elements in Series**
1-Label Based

In [ ]:
a1 = pd.Series([100,200,300,400], index = ['a','b','c','d'])
print(a1)

a    100
b    200
c    300
d    400
dtype: int64

In [ ]:
print(a1['d'])

400

**2 - Position - Based**

In [ ]:
a1 = pd.Series([100,200,300,400], index = ['a','b','c','d'])
print(a1)

a    100
b    200
c    300
d    400
dtype: int64

In [ ]:
print(a1[3])

400

/tmp/ipykernel_1350/3149581.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(a1[3])

**Slciing a Series**

In [ ]:
print(a1)

a    100
b    200
c    300
d    400
dtype: int64

we can use any of the methods for this sereies(slicing)

In [ ]:
print(a1[1:4])

b    200
c    300
d    400
dtype: int64

In [ ]:
print(a1['b':'d'])

b    200
c    300
d    400
dtype: int64

**Two more important methods for accessing value from data**
**1- .loc -> Label Based Access**

*   it is used to access data using index labels explicitly

In [ ]:
x1 = pd.Series([100,200,300,400,500], index = ['a','b','c','d','e'])
print(x1)

a    100
b    200
c    300
d    400
e    500
dtype: int64

In [ ]:
# single values
x1.loc['d']

np.int64(400)

In [ ]:
# multiple label values
x1.loc[['a','b','d']]

a    100
b    200
d    400
dtype: int64

In [ ]:
# label slicing
x1.loc['b':'d']

b    200
c    300
d    400
dtype: int64

**2- .iloc -> integer position - position**

In [ ]:
x1 = pd.Series([100,200,300,400,500], index = ['a','b','c','d','e'])
print(x1)

a    100
b    200
c    300
d    400
e    500
dtype: int64

In [ ]:
x1.iloc[3]

np.int64(400)

In [ ]:
x1.iloc[[2,3,4]]

c    300
d    400
e    500
dtype: int64

Operation on Series

In [ ]:
x1 = pd.Series([100,200,300,400,500], index = ['a','b','c','d','e'])
print(x1)

a    100
b    200
c    300
d    400
e    500
dtype: int64

In [ ]:
# add a number in a series(scaler addition)
print(x1+5)

a    105
b    205
c    305
d    405
e    505
dtype: int64

In [ ]:
# sub a number in a series(scaler addition)
print(x1-5)

a     95
b    195
c    295
d    395
e    495
dtype: int64

In [ ]:
# multiplication
print(x1*2)

a     200
b     400
c     600
d     800
e    1000
dtype: int64

In [ ]:
print(x1/2)

a     50.0
b    100.0
c    150.0
d    200.0
e    250.0
dtype: float64

In [ ]:
s1 = pd.Series([100,200,300,400])
s2 = pd.Series([500,600,700,800])
#element wise addition

In [ ]:
print(s1+s2)

0     600
1     800
2    1000
3    1200
dtype: int64

In [ ]:
print(s1-s2)

0   -400
1   -400
2   -400
3   -400
dtype: int64

In [ ]:
# note - Pandas match the data by index label
# if any label is missing -> Nan

In [ ]:
# Statistical Operations

In [ ]:
print(s1)

0    100
1    200
2    300
3    400
dtype: int64

In [ ]:
print("mean of a series-",s1.mean())
print("sum of series-",s1.sum())
print("max vlaue of a series-",s1.max())
print("min value of a series-",s1.min())
print("median of a series-",s1.median())
print("standard deviation of a series-",s1.std())
print("variance of series-",s1.var())

mean of a series- 250.0
sum of series- 1000
max vlaue of a series- 400
min value of a series- 100
median of a series- 250.0
standard deviation of a series- 129.09944487358058
variance of series- 16666.666666666668

**some more function -**

In [ ]:
# if you want to the stats summary of the data - data.describe()

In [ ]:
print(s1)

0    100
1    200
2    300
3    400
dtype: int64

In [ ]:
s1.describe()

count      4.000000
mean     250.000000
std      129.099445
min      100.000000
25%      175.000000
50%      250.000000
75%      325.000000
max      400.000000
dtype: float64

**Series Manupulation** it refers to changing values,index,datatype or structure of a series

In [ ]:
a = pd.Series([101,102,'a','pyhton',90,99])
print(a)

0       101
1       102
2         a
3    pyhton
4        90
5        99
dtype: object

In [ ]:
# updating the values
a[3] = 'Java'

In [ ]:
print(a)

0     101
1     102
2       a
3    Java
4      90
5      99
dtype: object

**apply()**--> it applies a custom function to each and every element of a series series.apply(function)

In [ ]:
z1 = pd.Series([100,200,300,400,5])
z1.apply(lambda i:i+10)

0    110
1    210
2    310
3    410
4     15
dtype: int64

In [ ]:
z1.apply(str)

0    100
1    200
2    300
3    400
4      5
dtype: object

replace()--> it will replace a specific value - syntax series.replace(value_replace,new_value)

In [ ]:
print(a)

0     101
1     102
2       a
3    Java
4      90
5      99
dtype: object

In [ ]:
a.replace(101,'sunday')

0    sunday
1       102
2         a
3      Java
4        90
5        99
dtype: object

**rename() **-> renames the index labels without changing original series

In [ ]:
print(a)

0     101
1     102
2       a
3    Java
4      90
5      99
dtype: object

In [ ]:
a.rename(index={0:'a',1:'b',2:'c',3:'d',4:'e',5:'f'})

a     101
b     102
c       a
d    Java
e      90
f      99
dtype: object

**Concatenation of a series**

In [ ]:
s1 = pd.Series([100,200,300,400,99])
s2 = pd.Series([500,600,700,800])
print(pd.concat([s1,s2]))

0    100
1    200
2    300
3    400
4     99
0    500
1    600
2    700
3    800
dtype: int64

**Conditional filtering and storing in a series**

In [ ]:
marks = pd.Series([45,78,88,32,95,33,41,28,19,18,17])
print(marks)

0     45
1     78
2     88
3     32
4     95
5     33
6     41
7     28
8     19
9     18
10    17
dtype: int64

In [ ]:
# syntax - series[condition]
marks[marks>60]

1    78
2    88
4    95
dtype: int64

In [ ]:
marks[(marks>60) &(marks<70)]

Series([], dtype: int64)

In [ ]:
# SORTING THE DATA -> ARRANGE THE DATA IN A SPECIFIC ORDER
# SOR THE DATA BY USING EITHER VALUES OR INDEX

In [ ]:
marks = pd.Series([45,78,88,32,95,33,41,28,19,18,17])
print(marks)

0     45
1     78
2     88
3     32
4     95
5     33
6     41
7     28
8     19
9     18
10    17
dtype: int64

In [ ]:
# sort_values() - sort the data based on their values

In [ ]:
marks.sort_values()

10    17
9     18
8     19
7     28
3     32
5     33
6     41
0     45
1     78
2     88
4     95
dtype: int64

In [ ]:
# by default data will sort in ascending order

In [ ]:
marks.sort_values(ascending=False)

4     95
2     88
1     78
0     45
6     41
5     33
3     32
7     28
8     19
9     18
10    17
dtype: int64

In [ ]:
# sort.index() - sort the data on index labels

In [ ]:
x = pd.Series([70,78,'a','i','red',34],index = ['hello','avni','riya','rahul','python','java'])
print(x)

hello      70
avni       78
riya        a
rahul       i
python    red
java       34
dtype: object

In [ ]:
x.sort_index()

avni       78
hello      70
java       34
python    red
rahul       i
riya        a
dtype: object

In [ ]:
x.index

Index(['hello', 'avni', 'riya', 'rahul', 'python', 'java'], dtype='object')

In [ ]:
x.values

array([70, 78, 'a', 'i', 'red', 34], dtype=object)

**DATAFRAME**
      * A dataframe is a 2 dimensional, labeled,tabular structure in Pandas
      * a table with rows and columns

**DataFrame = multiple series aligned by index**

In [ ]:
# creating a dataframe ---> pd.DataFrame()

In [ ]:
d1 = {'a':['raju','aman','amit','neha'],'b':[101,102,103,104],'c':['red','yellow','green','orange']}
print(d1)

{'a': ['raju', 'aman', 'amit', 'neha'], 'b': [101, 102, 103, 104], 'c': ['red', 'yellow', 'green', 'orange']}

In [ ]:
df1 = pd.DataFrame(d1)
# the keys in dictionary are acting here as column label

In [ ]:
df1

      a    b       c
0  raju  101     red
1  aman  102  yellow
2  amit  103   green
3  neha  104  orange

**from Excel/csv files**

In [ ]:
# df = pd.read_csv('file path')
# df = pd.read_excel('file path')

In [ ]:
df = pd.read_csv('/content/purchase_data.csv')

In [ ]:
df

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,1000001,P00069042,F,0-17,10.0,A,2,0.0,3.0,NaN,NaN,8370.0
1,1000001,P00248942,F,0-17,10.0,A,2,0.0,1.0,6.0,14.0,15200.0
2,1000001,P00087842,F,0-17,10.0,A,2,0.0,12.0,NaN,NaN,1422.0
3,1000001,P00085442,F,0-17,10.0,A,2,0.0,12.0,14.0,NaN,1057.0
4,1000002,P00285442,M,55+,16.0,C,4+,0.0,8.0,NaN,NaN,7969.0
...,...,...,...,...,...,...,...,...,...,...,...,...
263010,1004473,P00041942,M,36-45,1.0,B,3,0.0,5.0,18.0,NaN,3722.0
263011,1004473,P00115142,M,36-45,1.0,B,3,0.0,1.0,8.0,17.0,19253.0
263012,1004473,P00188442,M,36-45,1.0,B,3,0.0,5.0,7.0,NaN,3608.0
263013,1004473,P00119442,M,36-45,1.0,B,3,0.0,5.0,NaN,NaN,3604.0
263014,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

those who left the class from here you guys have to continue

In [ ]:
l1 = [[1,'avni',3],['a','b','c'],[10,30,20]]
print(l1)
df = pd.DataFrame(l1,columns=['random1','random2','random'])
print(df)

[[1, 'avni', 3], ['a', 'b', 'c'], [10, 30, 20]]
  random1 random2 random
0       1    avni      3
1       a       b      c
2      10      30     20

In [ ]:
df = pd.DataFrame(l1)

In [ ]:
df

    0     1   2
0   1  avni   3
1   a     b   c
2  10    30  20

**some basic DataFrame attrubutes**

In [ ]:
# df.shape --> gives the no. of rows and columns
df.shape

(3, 3)

In [ ]:
# df.columns --> displays all the column names which are present the data
df.columns

RangeIndex(start=0, stop=3, step=1)

In [ ]:
# df.dtypes --> data type of each columns
df.dtypes

0    object
1    object
2    object
dtype: object

In [ ]:
df1

      a    b       c
0  raju  101     red
1  aman  102  yellow
2  amit  103   green
3  neha  104  orange

In [ ]:
# 1 - selecting/accessing column
df1['b']

0    101
1    102
2    103
3    104
Name: b, dtype: int64

In [ ]:
df1[['a','c']]

      a       c
0  raju     red
1  aman  yellow
2  amit   green
3  neha  orange

In [ ]:
# selecting the rows
# loc --> label based

In [ ]:
df.loc[2]

0    10
1    30
2    20
Name: 2, dtype: object

In [ ]:
df.loc[0:2]

    0     1   2
0   1  avni   3
1   a     b   c
2  10    30  20

In [ ]:
# iloc -> integer position based access

In [ ]:
df.iloc[0]

0       1
1    avni
2       3
Name: 0, dtype: object

**Conditional filtering **

In [ ]:
df2 = pd.DataFrame({'name':['raj','siya','harman','yash'],'age':[24,21,19,17],'gender':['M','F','M','M']})
print(df2)

     name  age gender
0     raj   24      M
1    siya   21      F
2  harman   19      M
3    yash   17      M

In [ ]:
df2.drop('age',axis=1,inplace=False)

     name gender
0     raj      M
1    siya      F
2  harman      M
3    yash      M

In [ ]:
df2

     name  age gender
0     raj   24      M
1    siya   21      F
2  harman   19      M
3    yash   17      M

In [ ]:
df2[df2['age']>20]

   name  age gender
0   raj   24      M
1  siya   21      F

In [ ]:
df2[(df2['age']>20) & (df2['gender']=='F')]

   name  age gender
1  siya   21      F

In [ ]:
df2[df2['name']=='raj']

  name  age gender
0  raj   24      M

**DataFrame Manipulation**

In [ ]:
1- # Remove the columns

In [ ]:
print(df2)

     name gender
0     raj      M
1    siya      F
2  harman      M
3    yash      M

In [ ]:
df2.drop('age',axis=1,inplace=True)
# df2.drop(column=[],inplace=True)

In [ ]:
df2

     name gender
0     raj      M
1    siya      F
2  harman      M
3    yash      M

In [ ]:
# inplace = True ---> original DataFrame is changed permanently
# inplace = False(default) ---> original DataFrame is not changed instead of this it will give you a new dataframe

In [ ]:
# rename the columns -----> rename()
# df2.rename(columns={'old':'new_name'})

In [ ]:
# # Sorting Data
# .sort_values()
# .sort_index()

In [ ]:
# concatenation of DataFrame

In [ ]:
d1 = pd.DataFrame({"Id":[1,2],"Name":['A','B']})
d2 = pd.DataFrame({"Age":[28,29],"Grade":['C','D']})

In [ ]:
pd.concat([d1,d2],ignore_index=True)

    Id Name   Age Grade
0  1.0    A   NaN   NaN
1  2.0    B   NaN   NaN
2  NaN  NaN  28.0     C
3  NaN  NaN  29.0     D

In [ ]:
result =pd.concat(
    [df1,df2], #obj
    axis = 0,
    join='outer',
    ignore_index=True,
    keys=["first","Second"],
    sort=False,
    copy=True,
)
print(result)

      a      b       c    name   age gender
0  raju  101.0     red     NaN   NaN    NaN
1  aman  102.0  yellow     NaN   NaN    NaN
2  amit  103.0   green     NaN   NaN    NaN
3  neha  104.0  orange     NaN   NaN    NaN
4   NaN    NaN     NaN     raj  24.0      M
5   NaN    NaN     NaN    siya  21.0      F
6   NaN    NaN     NaN  harman  19.0      M
7   NaN    NaN     NaN    yash  17.0      M

In [ ]:
# groupby() ---> divide the data into groups

In [ ]:
x2 = pd.DataFrame({'city':["Banglore","Delhi","Banglore","Mumbai","Banglore"],"Sales":[30,40,50,60,70]})
print(x2)

       city  Sales
0  Banglore     30
1     Delhi     40
2  Banglore     50
3    Mumbai     60
4  Banglore     70

In [ ]:
result = x2.groupby('city', as_index=False).agg(
    Average_Sales=('Sales', 'mean')
)

print(result)

        city  Average_Sales
0  Bangalore           50.0
1      Delhi           40.0
2     Mumbai           60.0

In [ ]:
# avg sales based on city

In [ ]:
x2.groupby('city')['Sales'].mean()

city
Banglore    50.0
Delhi       40.0
Mumbai      60.0
Name: Sales, dtype: float64

**Handling the null or missing values**

In [ ]:
import numpy as np

In [ ]:
df2 = pd.DataFrame({'age':[10,20,np.nan],'gender':['m','f','f'],'name':['riya',np.nan,np.nan]})

In [ ]:
df2

    age gender  name
0  10.0      m  riya
1  20.0      f   NaN
2   NaN      f   NaN

In [ ]:
df2.isnull()

     age  gender   name
0  False   False  False
1  False   False   True
2   True   False   True

In [ ]:
df2.isnull().sum() # give the count of null values in each column
# df2.count()

age       2
gender    3
name      1
dtype: int64

In [ ]:
df2.isnull().sum().sum()

np.int64(3)

In [ ]:
# How to handle them??
# 1 - Delete the null values ---> df.dropna(inplace=True)
# 2 - fill the null values with other values(mean,median,mode,constant value) --> df.fillna(value,inplace=True)

In [ ]:
df2

    age gender  name
0  10.0      m  riya
1  20.0      f   NaN
2   NaN      f   NaN

In [ ]:
df2['age'].fillna(0,inplace=True)

/tmp/ipykernel_1350/270846370.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2['age'].fillna(0,inplace=True)

In [ ]:
df2

    age gender  name
0  10.0      m  riya
1  20.0      f   NaN
2   0.0      f   NaN

In [ ]:
df2.dropna(inplace = True)  # remove the entire row where null value is present

In [ ]:
df2

    age gender  name
0  10.0      m  riya

In [ ]:
df2.isnull().sum()

age       0
gender    0
name      0
dtype: int64

EDA(Exploratory Data Analysis)
  Understanding the data before building any model
  helps us to discover different patterns, clean data,and uncover relationships

In [ ]:
# Load the data
# view the data -> top rows, bottom rows
# understand the data-> Informaion, staistical summary about the data, shape
# check null values
# if we null values -> handle them
# check for duplicate values
# if we have duplicate values -> remove duplicate values
# column wise analysis
# outlier detection
# correlation

In [ ]:
import seaborn as sns

In [ ]:
df = sns.load_dataset('titanic') # in-built dataset