**Pandas **

It is a python library which is used for Data Manipulation and Data Analysis. It helps you to load, clean, Transform, analyze and explore the data. It stands for Pannel Data.

**Why was pandas created **
As we know Numpy is amazing for working with numbers, arrays and perform mathematical operations. But real - world data is messy :- missing values, mixed data, it is not clean,CSV/Excel file so, pandas was created to handle the real world problems, not only just for mathematics

**Pandas helps in -**

In [ ]:
# 1 - Load the dataset(CSV, Excel........)
# 2 - To clean the data(remove the null values, duplicate values, to handle null values,wrong values)
# 3 - to maipulate the data(filter, sort, group, merge...)
# 4 - to analyze the data for Machine Learning Models

In [ ]:
import pandas as pd

In [ ]:
# Pandas mainly has two structures -
# 1 - Series
# 2- DataFrame

**Series**
    it is one-dimensional array labeled array
    it is simply one column data with an index
    it can store number, string or mixed datatype

**Series = Data + Index**

In [ ]:
# Creating a Series -

**1- From a list**

In [ ]:
# to create a series ----> pd.Series
s = pd.Series([30,40,50,60,61,80,90])
print(s)

0    30
1    40
2    50
3    60
4    61
5    80
6    90
dtype: int64

In [ ]:
print(type(s))

<class 'pandas.core.series.Series'>

**2 - From a python dictionary**

In [ ]:
d1 = {'A':101, 'hii':102, 103:'Hello', 'A':'red'}
s2 = pd.Series(d1)
print(s2)
# Note - Keys in dictionary act as label
# values in dict act as data in series

A        red
hii      102
103    Hello
dtype: object

**3 - from tuple**

In [ ]:
t = (31,32,33,34,46)
s4 = pd.Series(t)
print(s4)

0    31
1    32
2    33
3    34
4    46
dtype: int64

In [ ]:
s = pd.Series([10,20,[30,40],50])
print(s)
print(type(s))

0          10
1          20
2    [30, 40]
3          50
dtype: object
<class 'pandas.core.series.Series'>

**4 - Custom Label/index**

In [ ]:
a1 = pd.Series([100,200,300,400], index = ['a','b','c','d'])
print(a1)

a    100
b    200
c    300
d    400
dtype: int64

**Accessing Elements in Series**
1-Label Based

In [ ]:
a1 = pd.Series([100,200,300,400], index = ['a','b','c','d'])
print(a1)

a    100
b    200
c    300
d    400
dtype: int64

In [ ]:
print(a1['d'])

400

**2 - Position - Based**

In [ ]:
a1 = pd.Series([100,200,300,400], index = ['a','b','c','d'])
print(a1)

a    100
b    200
c    300
d    400
dtype: int64

In [ ]:
print(a1[3])

400

/tmp/ipykernel_582/3149581.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(a1[3])

**Slciing a Series**

In [ ]:
print(a1)

a    100
b    200
c    300
d    400
dtype: int64

we can use any of the methods for this sereies(slicing)

In [ ]:
print(a1[1:4])

b    200
c    300
d    400
dtype: int64

In [ ]:
print(a1['b':'d'])

b    200
c    300
d    400
dtype: int64

**Two more important methods for accessing value from data**
**1- .loc -> Label Based Access**

*   it is used to access data using index labels explicitly

In [ ]:
x1 = pd.Series([100,200,300,400,500], index = ['a','b','c','d','e'])
print(x1)

a    100
b    200
c    300
d    400
e    500
dtype: int64

In [ ]:
# single values
x1.loc['d']

np.int64(400)

In [ ]:
# multiple label values
x1.loc[['a','b','d']]

a    100
b    200
d    400
dtype: int64

In [ ]:
# label slicing
x1.loc['b':'d']

b    200
c    300
d    400
dtype: int64

**2- .iloc -> integer position - position**

In [ ]:
x1 = pd.Series([100,200,300,400,500], index = ['a','b','c','d','e'])
print(x1)

a    100
b    200
c    300
d    400
e    500
dtype: int64

In [ ]:
x1.iloc[3]

np.int64(400)

In [ ]:
x1.iloc[[2,3,4]]

c    300
d    400
e    500
dtype: int64

Operation on Series

In [ ]:
x1 = pd.Series([100,200,300,400,500], index = ['a','b','c','d','e'])
print(x1)

a    100
b    200
c    300
d    400
e    500
dtype: int64

In [ ]:
# add a number in a series(scaler addition)
print(x1+5)

a    105
b    205
c    305
d    405
e    505
dtype: int64

In [ ]:
# sub a number in a series(scaler addition)
print(x1-5)

a     95
b    195
c    295
d    395
e    495
dtype: int64

In [ ]:
# multiplication
print(x1*2)

a     200
b     400
c     600
d     800
e    1000
dtype: int64

In [ ]:
print(x1/2)

a     50.0
b    100.0
c    150.0
d    200.0
e    250.0
dtype: float64

In [ ]:
s1 = pd.Series([100,200,300,400])
s2 = pd.Series([500,600,700,800])
#element wise addition

In [ ]:
print(s1+s2)

0     600.0
1     800.0
2    1000.0
3    1200.0
4       NaN
dtype: float64

In [ ]:
print(s1-s2)

0   -400.0
1   -400.0
2   -400.0
3   -400.0
4      NaN
dtype: float64